# Travis CI (MIT License) configuration file for WP Starter Theme
# @link https://travis-ci.org/

# Bionic image has PHP versions 7.1,7.2,7.3 pre-installed
dist: bionic

# Bionic does not start mysql or memcached by default
services:
  - mysql
  - memcached

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

branches:
  only:
    - master

# Git clone depth.
git:
  depth: 1

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=4.9 PHP_LINT=1
    - php: 7.3
      env: WP_VERSION=5.5 WP_PHPCS=1
    - php: 7.4
      env: WP_VERSION=latest
  fast_finish: true

before_script:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=6.1.*"

  # Set up WordPress.
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # Set up the WordPress installation.
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

    # Set up phpcs.
    - |
      if [[ "$WP_PHPCS" == "1" ]] ; then
        composer global require automattic/vipwpcs
        which phpcs
        phpcs --version
        phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs
      fi

    # For debugging.
    - which phpunit
    - phpunit --version
script:
  # Search for PHP syntax errors.
  #
  # Only need to run this once per PHP version.
  - |
    if [[ "$PHP_LINT" == "1" ]] ; then
      find . -type "f" -iname "*.php" -not -path "./vendor/*" | xargs -L "1" php -l
    fi

  # WordPress Coding Standards.
  #
  # These are the same across PHP and WordPress, so we need to run them only once.
  #
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  - |
    if [[ "$WP_PHPCS" == "1" ]] ; then
      phpcs
    fi

  # Run the plugin's unit tests, both in single and multisite.
  -
  - phpunit
  - WP_MULTISITE=1 phpunit

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
