sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=5.0
    - php: 7.3
      env: WP_VERSION=5.5 PHP_LINT=1
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_TRAVISCI=phpcs
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - composer install
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      chmod +x bin/setup-codesniffer.sh
      bash bin/setup-codesniffer.sh
      npm install --silent
    fi
script:
  - if [[ "$PHP_LINT" == "1" ]]; then  find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l

  # WordPress Coding Standards.
  #
  # These are the same across PHP and WordPress, so we need to run them only once.
  #
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  - if [[ "$WP_PHPCS" == "1" ]]; then phpcs; fi

  - phpunit
