sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=5.0
    - php: 7.3
      env: WP_VERSION=5.5 PHP_LINT=1
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_TRAVISCI=phpcs
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      chmod +x bin/setup-codesniffer.sh
      bash bin/setup-codesniffer.sh
      npm install --silent
    fi
script:
  - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      /tmp/wordpress/php-codesniffer/bin/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php
    fi
