sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=nightly
    - php: 7.2
      env: WP_VERSION=nightly
    - php: 7.0
      env: WP_TRAVISCI=phpcs
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      chmod +x bin/setup-codesniffer.sh
      bash bin/setup-codesniffer.sh
      composer install
      npm install --silent
    fi
script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      /tmp/wordpress/php-codesniffer/bin/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php
    fi
